const express = require('express')
const app = express()
const indexApi = require('./indexApi')
const adminApi = require('./adminApi')
const cors = require('cors')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use('/api/index',indexApi)
app.use('/api/admin',adminApi)
app.listen(3000,()=>{console.log('阳光彩虹小白马,开始监听中...')})